#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# fix for using a carrot in commands, e.g. "git reset HEAD^^"
setopt localoptions nonomatch

alias gits="git status -s"

function auth_me {
  ssh $1 'mkdir -p ~/.ssh'
  ssh $1 'cat >>.ssh/authorized_keys' <~/.ssh/id_rsa.pub
}
